version: "3"

services:

  db:
    image: mongo

    ports :
      - 27017:27017

    volumes:
      - ./data/db:/var/lib/mongodb/data
  
    environment : 
    
      - MONGO_INITDB_ROOT_USERNAME=amitsingh
      - MONGO_INITDB_ROOT_PASSWORD=onorall
      - MONGO_INITDB_DATABASE=myonorall
      - MONGO_INITDB_USERNAME=amitsingh
      - MONGO_INITDB_PASSWORD=onorall

  web:
      build: .
      
      command: python3 manage.py runserver 0.0.0.0:8000
      
      volumes:
        - .:/code

      ports:
        - "8080:8080"
      
      # env_file:
      #   - ./venv

      depends_on:
        - db




# version: '3'

# services:
#   web:
#     build: ./onorall-backend
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - ./app/:/usr/src/app/
#     ports:
#       - 8000:8000
#     env_file:
#       - ./.env.dev
#     depends_on:
#       - db
#   db:
#     image: mongo

#     ports :
#       - 27017:27017

#     volumes:
#       - mongo_data:/var/lib/mongodb/data
  
#     environment : 
    
#       - MONGO_INITDB_ROOT_USERNAME=amitsingh
#       - MONGO_INITDB_ROOT_PASSWORD=onorall
#       - MONGO_INITDB_DATABASE=myonorall
#       - MONGO_INITDB_USERNAME=amitsingh
#       - MONGO_INITDB_PASSWORD=onorall

# volumes:
#   mongo_data:

    