# Generated by Django 3.2.12 on 2022-03-22 05:23

from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20220321_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentss',
            name='dis_likes_on_comment',
            field=models.ManyToManyField(related_name='dis_likes_on_comment', to='myapp.sign'),
        ),
        migrations.AddField(
            model_name='commentss',
            name='likes_on_comment',
            field=models.ManyToManyField(related_name='likes_on_comment', to='myapp.sign'),
        ),
        migrations.AddField(
            model_name='reply',
            name='reply_of_reply',
            field=models.ManyToManyField(blank=True, related_name='_myapp_reply_reply_of_reply_+', to='myapp.Reply'),
        ),
        migrations.AlterField(
            model_name='addresources',
            name='resourcesid',
            field=models.CharField(default=myapp.models.random_id_field, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='basic_branding',
            name='brandingid',
            field=models.CharField(default=myapp.models.random_id_field, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='basic_display',
            name='highlightid',
            field=models.CharField(default=myapp.models.random_id_field, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='commentss',
            name='replies',
            field=models.ManyToManyField(blank=True, related_name='replies', to='myapp.Reply'),
        ),
        migrations.AlterField(
            model_name='commentss',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='myapp.sign'),
        ),
        migrations.AlterField(
            model_name='commentss',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_id', to='myapp.detail'),
        ),
        migrations.AlterField(
            model_name='connect',
            name='connectid',
            field=models.CharField(default=myapp.models.random_id_field, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='connect_comment',
            name='commentid',
            field=models.CharField(default=myapp.models.random_id_field, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='videoid',
            field=models.CharField(default=myapp.models.random_id_field, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='doc_verification',
            name='docid',
            field=models.CharField(default=myapp.models.random_id_field, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='groupskillid',
            field=models.CharField(default=myapp.models.random_id_field, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='grouplistid',
            field=models.CharField(default=myapp.models.random_id_field, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='textid',
            field=models.CharField(default=myapp.models.random_id_field, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='question2',
            name='qnaid',
            field=models.CharField(default=myapp.models.random_id_field, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='question3',
            name='mcqid',
            field=models.CharField(default=myapp.models.random_id_field, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='questionnaires',
            name='questionnaireid',
            field=models.CharField(default=myapp.models.random_id_field, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='report4',
            name='reportid',
            field=models.CharField(default=myapp.models.random_id_field, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='sectionid',
            field=models.CharField(default=myapp.models.random_id_field, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='sign',
            name='id',
            field=models.CharField(default=myapp.models.random_id_field, max_length=12, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='social_handling',
            name='socialid',
            field=models.CharField(default=myapp.models.random_id_field, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='timelinemodel',
            name='resourcesid',
            field=models.CharField(default=myapp.models.random_id_field, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='workbaseinfo',
            name='wbid',
            field=models.CharField(default=myapp.models.random_id_field, max_length=12, unique=True),
        ),
    ]
