# Generated by Django 3.2.12 on 2022-07-18 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import myapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0079_auto_20220712_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workbaseanalytics',
            name='active',
        ),
        migrations.RemoveField(
            model_name='workbaseanalytics',
            name='impressions',
        ),
        migrations.RemoveField(
            model_name='workbaseanalytics',
            name='name_of_action',
        ),
        migrations.RemoveField(
            model_name='workbaseanalytics',
            name='new_visit',
        ),
        migrations.RemoveField(
            model_name='workbaseanalytics',
            name='views',
        ),
        migrations.RemoveField(
            model_name='workbaseanalytics',
            name='visit',
        ),
        migrations.AddField(
            model_name='workbaseanalytics',
            name='analytic_options',
            field=models.CharField(choices=[('SEARCH', (('VIEW', 'VIEW'), ('IMPRESSIONS', 'IMPRESSIONS'), ('CPC', 'CPC'))), ('HOME', (('VIEW', 'VIEW'), ('IMPRESSIONS', 'IMPRESSIONS'), ('CPC', 'CPC'))), ('unknown', 'unknown')], default='unknown', max_length=25),
        ),
        migrations.AddField(
            model_name='workbaseanalytics',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workbaseanalytics',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workbaseanalytics',
            name='workbasename',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.workbaseinfo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addresources',
            name='resourcesid',
            field=models.CharField(default=myapp.models.random_id_field, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='basic_branding',
            name='brandingid',
            field=models.CharField(default=myapp.models.random_id_field, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='basic_display',
            name='highlightid',
            field=models.CharField(default=myapp.models.random_id_field, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='connect',
            name='connectid',
            field=models.CharField(default=myapp.models.random_id_field, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='connect_comment',
            name='commentid',
            field=models.CharField(default=myapp.models.random_id_field, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='videoid',
            field=models.CharField(default=myapp.models.random_id_field, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='doc_verification',
            name='docid',
            field=models.CharField(default=myapp.models.random_id_field, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='groupskillid',
            field=models.CharField(default=myapp.models.random_id_field, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='grouplistid',
            field=models.CharField(default=myapp.models.random_id_field, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='textid',
            field=models.CharField(default=myapp.models.random_id_field, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='question2',
            name='qnaid',
            field=models.CharField(default=myapp.models.random_id_field, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='question3',
            name='mcqid',
            field=models.CharField(default=myapp.models.random_id_field, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='questionnaires',
            name='questionnaireid',
            field=models.CharField(default=myapp.models.random_id_field, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='report4',
            name='reportid',
            field=models.CharField(default=myapp.models.random_id_field, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='sectionid',
            field=models.CharField(default=myapp.models.random_id_field, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='sign',
            name='id',
            field=models.CharField(default=myapp.models.random_id_field, max_length=12, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='social_handling',
            name='socialid',
            field=models.CharField(default=myapp.models.random_id_field, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='timelinemodel',
            name='resourcesid',
            field=models.CharField(default=myapp.models.random_id_field, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='workbaseinfo',
            name='wbid',
            field=models.CharField(default=myapp.models.random_id_field, max_length=12, unique=True),
        ),
    ]
